// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComdllSzSDFhh-z7pRwoZItVklxLL9REk',
    appId: '1:791496577507:web:6760d49d039fcdafb010d6',
    messagingSenderId: '791496577507',
    projectId: 'ecomerceapp-17a93',
    authDomain: 'ecomerceapp-17a93.firebaseapp.com',
    storageBucket: 'ecomerceapp-17a93.firebasestorage.app',
    measurementId: 'G-CFBJW8SLQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg1zr6yZIvddRcqdS7g7839c97W4o-DCQ',
    appId: '1:791496577507:android:b48dbb934f3fece8b010d6',
    messagingSenderId: '791496577507',
    projectId: 'ecomerceapp-17a93',
    storageBucket: 'ecomerceapp-17a93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlYOAIBh57cVJiipFh7TC4LuD0nI1afjs',
    appId: '1:791496577507:ios:1a59623bcdd997f3b010d6',
    messagingSenderId: '791496577507',
    projectId: 'ecomerceapp-17a93',
    storageBucket: 'ecomerceapp-17a93.firebasestorage.app',
    iosBundleId: 'com.example.ecomerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlYOAIBh57cVJiipFh7TC4LuD0nI1afjs',
    appId: '1:791496577507:ios:1a59623bcdd997f3b010d6',
    messagingSenderId: '791496577507',
    projectId: 'ecomerceapp-17a93',
    storageBucket: 'ecomerceapp-17a93.firebasestorage.app',
    iosBundleId: 'com.example.ecomerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComdllSzSDFhh-z7pRwoZItVklxLL9REk',
    appId: '1:791496577507:web:3c5298dab2a4ca60b010d6',
    messagingSenderId: '791496577507',
    projectId: 'ecomerceapp-17a93',
    authDomain: 'ecomerceapp-17a93.firebaseapp.com',
    storageBucket: 'ecomerceapp-17a93.firebasestorage.app',
    measurementId: 'G-CHQVESQ48J',
  );
}
